config/routes.rb
Rails.application.routes.draw do
  get "/" => "users#top"
  get "/about" => "users#about"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'

  resources :books
  resources :books, only: [:new, :create, :index, :show, :destroy, :new] do
  	resource :post_comments, only: [:create, :destroy] #コメント機能
    resource :favorites, only: [:create, :destroy]  #お気に入り
  end
  resources :users, only: [:show, :edit, :update,:index] do
    resources :favorites, only: [:index]  #お気に入り
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
#検索機能------
	def self.search(search)
      if search
        Book.where(['title LIKE ?', "%#{search}%"])#titleの部分に検索したい部分一致のカラムを入れる
      else
        Book.all
      end
    end
#-------------
 #belongs_to :user
 has_many :post_comments, dependent: :destroy
 has_many :favorites, foreign_key: 'book_id', dependent: :destroy #お気に入り
 has_many :users, through: :favorites #お気に入り

 validates :title, presence: true
 validates :opinion, presence: true,length: {maximum: 200}


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :book

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :books,through: :favorites, dependent: :destroy
    has_many :post_comments, dependent: :destroy #コメント機能
    has_many :favorites       #お気に入り
    has_many :favposts, through: :favorites, source: :book #お気に入り

  

    attachment :profile_image

    validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 20}
    validates :introduction, length: {maximum: 50}

    def email_required?
   false
 	end
 	def email_changed?
   false
 	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, except: [:top,:about]
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(current_user.id)
end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        #@books = Book.all
        @books = Book.search(params[:search]) #検索機能
        @book = Book.new
        @user = current_user
    end

	def new
		@book = Book.new
    end

    def users
        @users = User.all
    end

    def books
    end


    def create
        @books = Book.all
    	@book = Book.new(book_params)
        @user = current_user
        @book.user_id = current_user.id
    	if @book.save
        flash[:success] = "Book is successfully!!!!"
    	redirect_to book_path(@book.id)
        else
        render :index
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def show
    	@book = Book.find(params[:id])
        @book_new = Book.new
        @post_comment = PostComment.new  #コメント機能
        @favorite = Favorite.new #お気に入り
        @user = current_user
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:update] = "Book was successfully update(^o^)/~~"
            redirect_to book_path(@book.id)
        end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end

 private
    def book_params
        params.require(:book).permit(:title, :opinion)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
  	@favorites = Favorite.all
  end

  def create
  	user = current_user
  	book = Book.find(params[:book_id])
    Favorite.create(user_id: user.id,book_id:book.id)
    redirect_to books_path
  end

  def destroy
  	user=current_user
  	book = Book.find(params[:book_id])
    favorite=Favorite.find_by(user_id: user.id,book_id:book.id)
      favorite.delete
      redirect_to user_favorites_path(current_user)
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
		book = Book.find(params[:book_id])
	    comment = current_user.post_comments.new(post_comment_params)
	    comment.book_id = book.id
	    comment.save
	    redirect_to book_path(book)
	end

	private

	def post_comment_params
	  params.require(:post_comment).permit(:user_id,
	                      :book_id,
	                      :comment)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end

  def about
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	 @user = User.find(params[:id])
  	 @book = Book.new
     @books_user = Book.where(user_id: params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
        flash[:userinfo_update] = "User is successfully!!!!!!!!!!!!!!!!!"
        redirect_to user_path(@user.id)
    else
      render :edit
    end
  end



private
	def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/books/_list.html.erb
<section class="sideber">
<% if current_user %>
  <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: 'no_image.jpg' %>
      <table class="table">
        <tbody>
           <tr>
            <th>name</th>
            <th><%= user.name %></th>
           </tr>

           <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
           </tr>
           <tr>
             <th>
              <% if user.id == current_user.id %>
               <p>
                <button type="button" class="btn btn-default"><%= link_to edit_user_path(user), class: "edit_user_#{user.id}" do %>
                  <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
                <% end %>
               </p>
             </th>
            </tr>
            <% end %>
        </tbody>
      </table>
  <% end %>

  <h3>New book</h3>
<%= form_for(book) do |f| %>
 <% if book.errors.any? %>
  <div id="error_explanation">
      <h3><%= book.errors.count %>Error!!</h3>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>


<h4>Title</h4>
<div class="form-group">
<%= f.text_field :title, class: "book_title" %></div>

<h4>Opnion</h4>
<div class="form-group">
<%= f.text_field :opinion, class: "book_body" %></div>

<%= f.submit "Create Book" ,class: "btn btn-primary" %>

<% end %>
</section>

app/views/books/books.html.erb

<%= render 'books/list', books: @books, book: @book, user: @user %>

<sectin class="title clearfix"><h2>Books</h2>
 <table class="table clearfix">
  <thead>
   <tr>
    <th>Title</th>
    <th>&nbsp;Opinion</th>
    <th></th>
   </tr>
  </thead>

		<tbody>
  <% @users.each do |user| %>
    <tr>
     <td>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      <%= link_to book.title, book_path(book.id), class: "show_#{book.id}" %>
      </td>
     <td>&nbsp;&nbsp;<%= book.opinion %></td>
    </tr>

   <% end %>
  </tbody>
 </table>
</sectin>
<div>
&nbsp;
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title, class: "book_title" %>

    <h4>Opinion</h4>
    <%= f.text_area :opinion, class: "book_body" %>

    <br><%= f.submit "Update Book", class: "btn btn-primary" %><br>
<% end %>

<%= link_to "Show",book_path, class: 'show_#{@book.id}' %>
<%= link_to "Back","/books",  class: 'back' %>

app/views/books/index.html.erb

<%= render 'books/list', book: @book, user: @user %>
<!--検索機能------->
<sectin class="title clearfix"><h2>Books</h2>
  <p>search</p>
<%= form_tag(books_path, :method => 'get' ) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :title => nil %>
<% end %>
<!--検索機能------->
  <table class="table clearfix">
    <thead>
     <tr>
  	  <th>Title</th>
  	  <th>&nbsp;Opinion</th>
  	  <th></th>
     </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
    	   <td>
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
          <%= link_to book.title, book_path(book.id), class: "show_#{book.id}" %>
<!-----お気に入り--->
              

             <% if !Favorite.exists?(user_id:current_user.id,book_id:book.id) %>
              <%= link_to "お気に入り",book_favorites_path(book),method: :post %>
              <% else %>
              <%= link_to "お気に入り解除",book_favorites_path(book),method: :delete %>
              <% end %>

<!------------------->
          </td>
    	   <td>&nbsp;&nbsp;<%= book.opinion %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</sectin>
<div>
&nbsp;
</div>

app/views/books/new.html.erb
<%= render 'books/list', books: @books %>

app/views/books/show.html.erb
<%= render 'books/list', books: @books, book: @book_new, user: @user %>

<div class="flash">
  <%= flash[:success] %>
</div>
<div class="flash">
  <%= flash[:update] %>
</div>



 <section class="title clearfix">
  <h1>Book detail</h1>
   <table class="table">
   	  <tr>
   	 	<td>
   	 	<%= link_to user_path(@user.id),class: "user_#{@user.id}" do %>
   	 	<%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %><br>
   	 		<%= current_user.name %>
   	 	<% end %>
   	    </td>
   	    <td>
	 	<%= @book.title %>
	 	</td>
	 	<td>
	 	<%= @book.opinion %>&nbsp;&nbsp;
	 	</td>
	 	<td>
	 	<% if  current_user %>
	 	<button class="btn btn-success"><%= link_to "Edit",edit_book_path(@book.id), class: 'edit_book_#{@book.id}' %></button>
	 	<% end %>
	    </td>
	    <td>
	 	<% if current_user %>
		<button class="btn btn-danger"><%= link_to "Destroy", book_path(@book.id), class: "destroy_book_#{@book.id}", method: :delete, "data-confirm" => "本気？本当に消すんですか?" %></button>
		 <% end %>
		</td>
	  </tr>
   </table>
<!--コメント機能-->
  <%= form_for [@book, @post_comment] do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_field :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

<div class="line-bc">
  <% @book.post_comments.each do |post_comment| %>
   		<li class="comment">
   		</style>
            <div class="comment-body bb">
                <div class="comment-text">
                    <div class="comment-author clearfix">
                        <%= post_comment.user.name %>さん
                        <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                    </div>
                    <div class="balloon6">
                    	<div class="chatting">
                          <div class="faceicon">
                            <%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg" %>
                          </div>
        						      <div class="says">
                      		  <%= post_comment.comment %>
                      		</div>
                    	</div>
                    </div>
                </div>
            </div>
        </li>
    <% end %>
</div>
<!--------------------->
</section>

app/views/favorites/index.html.erb
<h2>My Favorite</h2>

<% @favorites.each do |favorite| %>
	<div class="">
		<table>
			<tr>
				<td class="col-lg-6">
                    <%= link_to book_path(favorite.book.id) do %>
					商品名：<%= favorite.book.title %><br>
                    <% end %>
                </td>
				<td class="col-lg-6">
				<%= link_to 'お気に入りを解除する', book_favorites_path(favorite.book.id), method: :delete, class: "btn btn bg-info" %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
    <h2>Bookers</h2>
    <nav>
      <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>
      <li>
        <%= link_to 'Home', user_path(current_user.id),class: "home", class: "glyphicon glyphicon-home" %>
      </li>

      <li>
        <%= link_to 'お気に入り', user_favorites_path(current_user.id), class: "glyphicon glyphicon-home" %>
      </li>


      <li>
        <%= link_to 'Users', users_path,class: "users", class: "glyphicon glyphicon-user" %>
      </li>

      <li>
        <%= link_to 'Books', books_path,class: "books", class: "glyphicon glyphicon-book" %>
      </li>

      <li>
      <%= link_to "Logout", destroy_user_session_path, class: "logout", class: "glyphicon glyphicon-log-out", method: :delete %>
      </li>

      <% else %>
      <li>
        <%= link_to 'Home', "/",class: "home", class: "glyphicon glyphicon-home" %>
      </li>

      <li>
        <%= link_to "About", about_path,class: "about", class: "glyphicon glyphicon-link" %>
      </li>

      <li>
        <%= link_to "Sign up", new_user_registration_path,class: "sign_up", class: "glyphicon glyphicon-edit" %>
      </li>

      <li>
        <%= link_to "Sign in",new_user_session_path, class: "sign_in", class: "glyphicon glyphicon-log-in" %>
      </li>
    <% end %>
  </ul>
</nav>
</header>
<div class="container">
  <div class="row">
    <%= yield %>

  </div>
</div>
<footer>
  <p>CopyRight Infratop.inc</p>
</footer>

</body>


</html>

app/views/users/about.html.erb
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong> !!</h1>

app/views/users/edit.html.erb
<section class="userinfo">
	<h1>User info</h1>
 	<%= form_for(@user) do |f| %>
		<div class="namelabel">
       	 <label for="name">Name</label>
        	<%= f.text_field :name, class: "name", autofocus: true, id:"inputEmail", placeholder:"user[name]" %>
   		 </div>

    	<div class="imagelabel">
     		<label class="control-label sr-only" for="inputEmail">Image</label>
    		<%= f.attachment_field :profile_image, class: "user_image", placeholder: "ファイルを選択" %>
    	</div><br>

    	<div class="introductionlabel">
     		<label for="introduction">Introduction</label>
                <% if @user.errors.any? %>
                  <div id="error_explanation">
                    <ul>
                      <% @user.errors.full_messages.each do |message| %>
                        <li>Error！！<%= message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
        		<%= f.text_field :introduction, class: "introduction", autofocus: true, id:"inputEmail",size:"30*20" %>
        </div>

         <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb

<%= render 'books/list',book: @book, user: @user %>

<sectin class="title clearfix">
  <h2>Users</h2>
	<table class="table clearfix">
  	 <thead>
      <tr>
	   <th>image&nbsp;&nbsp;&nbsp;name</th>
	   <th></th>
      </tr>
  	 </thead>
  	 <tbody>

		<% @users.each do |user| %>
	<tr>
	   <td>
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
       <%= user.name %>
      </td>
	   <td>&nbsp;&nbsp;<%= link_to "Show", user_path(user.id), class: "show_#{user.id}" %></td>
    </tr>
    <% end %>
    </tbody>
 </table>
</sectin>
<div>
&nbsp;
</div>

app/views/users/show.html.erb
<% if user_signed_in? %>
<p><%= notice %></p>

<%= render 'books/list',book: @book, user: @user %>

<div class="flash">
  <%= flash[:userinfo_update] %>
</div>

<section class="title clearfix">
<h1>Books</h1>
 <table class="table table-hover">
  <thead>
   <tr>
    <th>Title</th>
    <th>&nbsp;Opinion</th>
    <th></th>
   </tr>
  </thead>

 <tbody>
  <% @books_user.each do |book| %>
    <tr>
        <td>
         <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
        <%= link_to book.title, book_path(book.id), class: "show_#{book.id}" %>
        </td>
        <td><%= book.opinion %></td>
    </tr>
   <% end %>
  </tbody>
 </table>

<% end %>



app/views/users/top.html.erb
<section class="top">
<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers</strong> !!</h1>
<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p><br>

<p>you can share and exchange your opinions , inpressions , and emotions</p><br>

<p>about varioius books!</p>

<button class="btn btn-info btn-block">
	<%= link_to "Sign in",new_user_session_path, class: "sign_in" %>
	</button><br>
<button class="btn btn-success btn-block"><%= link_to "Sign up",new_user_registration_path,class: "sign_up" %></button>
</section>